# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  push:
    branches: [ master ]

jobs:
  pull:

    runs-on: self-hosted

    steps:
      
    - name: git pull 
      run: |
        git pull origin master
        echo ${{ github.event_path }} >> log/test.log